-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 13:49:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema business
-- -----------------------------------------------------
-- 业务库
DROP SCHEMA IF EXISTS `business` ;

-- -----------------------------------------------------
-- Schema business
--
-- 业务库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `business` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
-- -----------------------------------------------------
-- Schema perfect-fs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `perfect-fs` ;

-- -----------------------------------------------------
-- Schema perfect-fs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perfect-fs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `business` ;

-- -----------------------------------------------------
-- Table `business`.`m_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`m_user` ;

CREATE TABLE IF NOT EXISTS `business`.`m_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL COMMENT '用户实名',
  `simple_name` VARCHAR(45) NULL COMMENT '简称',
  `type` VARCHAR(2) NULL COMMENT '系统用户=10,职员=20,客户=30,供应商=40,其他=50,认证管理员=60,审计管理员=70',
  `descr` VARCHAR(255) NULL COMMENT '描述',
  `pwd` VARCHAR(255) NULL COMMENT '密码\n',
  `isdel` TINYINT(1) NULL COMMENT '是否是已经删除\n',
  `islock` TINYINT(1) NULL COMMENT '是否锁定\n',
  `isenable` TINYINT(1) NULL COMMENT '是否禁用\n',
  `effective_date` DATETIME NULL COMMENT '生效时间\n',
  `invalidation_date` DATETIME NULL COMMENT '失效时间\n',
  `err_count` INT NULL COMMENT '登录错误次数\n',
  `group_id` VARCHAR(45) NULL COMMENT '所属用户组\n用户组织范围\n包含下级组织的组织范围\n',
  `staff_id` BIGINT NULL,
  `pwd_effective_date` DATETIME NULL COMMENT '密码生效日期\n',
  `locked_time` DATETIME NULL COMMENT '用户锁定时间',
  `is_biz_admin` TINYINT(1) NULL COMMENT '是否为业务管理员',
  `is_changed_pwd` TINYINT(1) NULL COMMENT '是否修改过密码',
  `login_author_way` TINYINT(1) NULL COMMENT '传统认证方式=0,智能钥匙认证=1,动态密码锁=2,指纹认证方式=3',
  `pwd_his_pwd` VARCHAR(255) NULL COMMENT '历史密码',
  `email` VARCHAR(100) NULL,
  `home_telno` VARCHAR(45) NULL COMMENT '家庭电话',
  `office_telno` VARCHAR(45) NULL COMMENT '办公室电话',
  `cell_telno` VARCHAR(45) NULL COMMENT '手机号码',
  `corp_code` VARCHAR(20) NULL COMMENT '租户代码',
  `corp_name` VARCHAR(100) NULL COMMENT '租户名称',
  `sex` TINYINT(1) NULL COMMENT '性别',
  `avatar` VARCHAR(255) NULL COMMENT '头像路径',
  `last_login_date` DATETIME NULL COMMENT '最后登陆时间',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  UNIQUE INDEX `login_name_UNIQUE` (`login_name` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户主表';


-- -----------------------------------------------------
-- Table `business`.`j_job_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`j_job_master` ;

CREATE TABLE IF NOT EXISTS `business`.`j_job_master` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `job_name` VARCHAR(200) NULL COMMENT '任务名称',
  `job_serial_code` VARCHAR(45) NULL COMMENT '任务编号',
  `job_desc` VARCHAR(200) NULL COMMENT '任务描述',
  `job_simple_name` VARCHAR(45) NULL COMMENT '任务简称',
  `bean_name` VARCHAR(255) NULL COMMENT 'Bean名称',
  `method_name` VARCHAR(255) NULL COMMENT '方法名称',
  `params` VARCHAR(1000) NULL COMMENT '参数',
  `cron_expression` VARCHAR(255) NULL COMMENT '表达式',
  `isdel` TINYINT(1) NULL COMMENT '是否是已经删除\n',
  `is_effected` TINYINT(1) NULL COMMENT '是否有效',
  `run_time` DATETIME NULL COMMENT '下次运行时间',
  `last_run_time` DATETIME NULL COMMENT '上次运行时间',
  `begin_date` DATETIME NULL COMMENT '起始有效时间',
  `end_date` DATETIME NULL COMMENT '结束有效时间',
  `run_times` INT NULL COMMENT '运行次数',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '任务主表';


-- -----------------------------------------------------
-- Table `business`.`j_job_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`j_job_log` ;

CREATE TABLE IF NOT EXISTS `business`.`j_job_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `job_name` VARCHAR(200) NULL COMMENT '任务名称',
  `job_serial_code` VARCHAR(45) NULL COMMENT '任务编号',
  `job_desc` VARCHAR(200) NULL COMMENT '任务描述',
  `job_simple_name` VARCHAR(45) NULL COMMENT '任务简称',
  `bean_name` VARCHAR(255) NULL COMMENT 'Bean名称',
  `method_name` VARCHAR(255) NULL COMMENT '方法名称',
  `params` VARCHAR(1000) NULL COMMENT '参数',
  `cron_expression` VARCHAR(255) NULL COMMENT '表达式',
  `isdel` TINYINT(1) NULL COMMENT '是否是已经删除\n',
  `is_effected` TINYINT(1) NULL COMMENT '是否有效',
  `next_run_time` DATETIME NULL COMMENT '下次运行时间',
  `last_run_time` DATETIME NULL COMMENT '上次运行时间',
  `begin_date` DATETIME NULL COMMENT '起始有效时间',
  `end_date` DATETIME NULL COMMENT '结束有效时间',
  `run_times` INT NULL COMMENT '运行次数',
  `status` TINYINT(1) NULL,
  `error` VARCHAR(255) NULL COMMENT '异常信息',
  `cost` BIGINT NULL COMMENT '耗时（毫秒）',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '任务执行日志表';


-- -----------------------------------------------------
-- Table `business`.`s_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_log` ;

CREATE TABLE IF NOT EXISTS `business`.`s_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL COMMENT '操作用户',
  `operation` VARCHAR(45) NULL COMMENT '操作描述',
  `time` BIGINT NULL COMMENT '耗时（毫秒）',
  `class_name` VARCHAR(255) NULL,
  `class_method` VARCHAR(45) NULL,
  `http_method` VARCHAR(10) NULL COMMENT 'HTTP方法',
  `params` VARCHAR(2000) NULL COMMENT '参数',
  `url` VARCHAR(255) NULL COMMENT 'url',
  `ip` VARCHAR(45) NULL COMMENT 'IP地址',
  `c_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '日志表';


-- -----------------------------------------------------
-- Table `business`.`m_user_lite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`m_user_lite` ;

CREATE TABLE IF NOT EXISTS `business`.`m_user_lite` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `login_name` VARCHAR(45) NULL,
  `name` VARCHAR(200) NULL,
  `simple_name` VARCHAR(45) NULL,
  `type` VARCHAR(20) NULL COMMENT '系统用户=10,职员=20,客户=30,供应商=40,其他=50,认证管理员=60,审计管理员=70',
  `descr` VARCHAR(255) NULL COMMENT '描述',
  `pwd` VARCHAR(255) NULL COMMENT '密码\n',
  `corp_code` VARCHAR(20) NULL COMMENT '租户代码',
  `corp_name` VARCHAR(100) NULL COMMENT '租户名称',
  `avatar` VARCHAR(255) NULL COMMENT '头像',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_name_UNIQUE` (`login_name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '用户表 简单';


-- -----------------------------------------------------
-- Table `business`.`s_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_role` ;

CREATE TABLE IF NOT EXISTS `business`.`s_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(2) NULL COMMENT '角色类型',
  `code` VARCHAR(20) NULL COMMENT '角色编码',
  `name` VARCHAR(100) NULL COMMENT '角色名称',
  `descr` VARCHAR(200) NULL COMMENT '描述',
  `simple_name` VARCHAR(45) NULL COMMENT '简称',
  `isdel` TINYINT(1) NULL COMMENT '是否是已经删除(1:true-已删除,0:false-未删除)\n',
  `isenable` TINYINT(1) NULL COMMENT '是否禁用(1:true-未启用,0:false-已启用)\n\n',
  `corp_code` VARCHAR(20) NULL COMMENT '租户代码',
  `corp_name` VARCHAR(100) NULL COMMENT '租户名称',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `business`.`m_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`m_staff` ;

CREATE TABLE IF NOT EXISTS `business`.`m_staff` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userid` BIGINT NULL COMMENT '用户',
  `deptid` BIGINT NULL,
  `code` VARCHAR(20) NULL COMMENT '编码',
  `descr` VARCHAR(255) NULL COMMENT '描述',
  `birthday` DATE NULL COMMENT '生日',
  `office_telno` VARCHAR(45) NULL,
  `idcardno` VARCHAR(45) NULL,
  `iswed` TINYINT(1) NULL COMMENT '婚否',
  `nation` VARCHAR(3) NULL COMMENT '名族',
  `service` TINYINT(1) NULL COMMENT '是否在职\n在职=1,不在职=0,离职=2,离退休=3,返聘=4',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '员工';


-- -----------------------------------------------------
-- Table `business`.`s_log_oper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_log_oper` ;

CREATE TABLE IF NOT EXISTS `business`.`s_log_oper` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作日志记录',
  `title` VARCHAR(45) NULL COMMENT '模块标题',
  `business_type` INT NULL COMMENT '业务类型（0其它 1新增 2修改 3删除）',
  `method` VARCHAR(255) NULL COMMENT '方法名称',
  `operator_type` INT NULL COMMENT '操作类别（0其它 1后台用户 2手机端用户）',
  `oper_name` VARCHAR(100) NULL COMMENT '操作人员',
  `dept_name` VARCHAR(100) NULL COMMENT '部门名称',
  `url` VARCHAR(255) NULL COMMENT '请求URL',
  `ip` VARCHAR(20) NULL COMMENT 'ip',
  `location` VARCHAR(255) NULL COMMENT '操作地点',
  `param` VARCHAR(2000) NULL COMMENT '操作状态（0正常 1异常）',
  `status` TINYINT(1) NULL COMMENT '操作状态（0正常 1异常）',
  `error_msg` VARCHAR(2000) NULL COMMENT '操作时间',
  `oper_time` DATETIME NULL COMMENT '操作时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '日志表';


-- -----------------------------------------------------
-- Table `business`.`s_log_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_log_access` ;

CREATE TABLE IF NOT EXISTS `business`.`s_log_access` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作日志记录',
  `login_name` VARCHAR(45) NULL COMMENT '模块标题',
  `ip` VARCHAR(20) NULL COMMENT '业务类型（0其它 1新增 2修改 3删除）',
  `location` VARCHAR(255) NULL COMMENT '方法名称',
  `browser` VARCHAR(45) NULL COMMENT '操作类别（0其它 1后台用户 2手机端用户）',
  `os` VARCHAR(45) NULL COMMENT '操作人员',
  `status` TINYINT(1) NULL COMMENT '部门名称',
  `msg` VARCHAR(255) NULL COMMENT '请求URL',
  `access_time` DATETIME NULL COMMENT 'ip',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '日志表';


-- -----------------------------------------------------
-- Table `business`.`s_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_resource` ;

CREATE TABLE IF NOT EXISTS `business`.`s_resource` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(2) NULL COMMENT 'excel导入模板文件：10，静态配置文件：20，静态图片文件：30，json\n',
  `name` VARCHAR(40) NULL COMMENT '资源名称',
  `uri` VARCHAR(200) NULL COMMENT '相对路径',
  `base` VARCHAR(200) NULL COMMENT '文件系统的baseurl',
  `size` BIGINT NULL COMMENT '文件大小',
  `extension` VARCHAR(10) NULL COMMENT '文件扩展名',
  `corp_code` VARCHAR(20) NULL COMMENT '租户代码',
  `corp_name` VARCHAR(100) NULL COMMENT '租户名称',
  `descr` VARCHAR(200) NULL COMMENT '描述',
  `context` JSON NULL COMMENT 'json配置信息',
  `isdel` TINYINT(1) NULL COMMENT '是否删除',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `c_id` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '资源表';


-- -----------------------------------------------------
-- Table `business`.`s_dict_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_dict_type` ;

CREATE TABLE IF NOT EXISTS `business`.`s_dict_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(20) NULL COMMENT '字典名称',
  `code` VARCHAR(20) NULL COMMENT '字典编号：唯一',
  `descr` VARCHAR(200) NULL COMMENT '描述',
  `isdel` TINYINT(1) NULL COMMENT '是否删除',
  `corp_code` VARCHAR(20) NULL,
  `corp_name` VARCHAR(100) NULL,
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '字典类型表、字典主表';


-- -----------------------------------------------------
-- Table `business`.`s_dict_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_dict_data` ;

CREATE TABLE IF NOT EXISTS `business`.`s_dict_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dict_id` BIGINT NULL COMMENT '字典主键',
  `sort` TINYINT NULL COMMENT '字典排序',
  `label` VARCHAR(100) NULL COMMENT '字典标签',
  `value` VARCHAR(100) NULL COMMENT '字典键值',
  `descr` VARCHAR(200) NULL COMMENT '描述',
  `isdel` TINYINT(1) NULL COMMENT '是否删除',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '字典数据表';


-- -----------------------------------------------------
-- Table `business`.`s_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business`.`s_config` ;

CREATE TABLE IF NOT EXISTS `business`.`s_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL COMMENT '参数名称',
  `key` VARCHAR(20) NULL,
  `value` VARCHAR(20) NULL COMMENT '参数键名',
  `descr` VARCHAR(200) NULL COMMENT '描述',
  `isdel` TINYINT(1) NULL COMMENT '是否删除',
  `c_id` BIGINT NULL,
  `c_time` DATETIME NULL,
  `u_id` BIGINT NULL,
  `u_time` DATETIME NULL,
  `dbversion` INT NULL DEFAULT 0 COMMENT '数据版本，乐观锁使用',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '参数配置表';

USE `perfect-fs` ;

-- -----------------------------------------------------
-- Table `perfect-fs`.`s_file_repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfect-fs`.`s_file_repository` ;

CREATE TABLE IF NOT EXISTS `perfect-fs`.`s_file_repository` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `file_uuid` VARCHAR(20) NULL COMMENT '文件的uuid',
  `file_name` VARCHAR(200) NULL COMMENT '文件名',
  `file_size` BIGINT NULL COMMENT '文件大小',
  `relative_path` VARCHAR(100) NULL COMMENT '路径',
  `create_dt` DATETIME NULL COMMENT '生成日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
